[build]
command = "npm run build && cp debug/serverSideTranslations.js node_modules/next-i18next/dist/commonjs"
publish = "out"

[functions]
included_files = ["next-i18next.config.js", "public/*"]

[[plugins]]
package = "@netlify/plugin-nextjs"
