[build]
command = "cp -v debug/serverSideTranslations.js node_modules/next-i18next/dist/commonjs && cat node_modules/next-i18next/dist/commonjs/serverSideTranslations.js && npm run build"
publish = "out"

[functions]
included_files = ["next-i18next.config.js", "public/*"]

[[plugins]]
package = "@netlify/plugin-nextjs"
